language: julia

os:
    - osx
    - linux

julia:
    - 1.2
    - nightly

codecove: true

notifications:
    email: false

after_success:
- julia -e 'cd(Pkg.dir("AbstractIndices")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
